### PR TITLE
Adding attribute to handle with sysctl -e flag

### PR DESCRIPTION
**Pull request by jiokmiso**
### Description

This change would allow using -e for sysctl command through additional attribute node['sysctl']['ignore_error']. 

### Issues Resolved

N/A

### Check List
- [x] All tests pass. See https://github.com/chef-brigade/sysctl/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Lgtm

**Comment by jiokmiso** [comment]
Hi, do you have any plan for releasing this feature in near future? Thanks.

**Comment by damacus** [comment]
Looks at releasing it tonight 👍

**Comment by isuftin** [comment]
Any update as to when a new release will happen?

**Comment by damacus** [comment]
I didn't get it done the other day we're sorting out logins and other things.
It's on my list for tomorrow

**Pull request merged**
